# This template file will have its environment variables expanded
# and the .template extension removed by the bash-template Wercker step.
# See wercker.yml.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quickstart-mp
  labels:
    commit: ${WERCKER_GIT_COMMIT}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickstart-mp
  template:
    metadata:
      labels:
        app: quickstart-mp
        commit: ${WERCKER_GIT_COMMIT}
    spec:
      containers:
      - name: quickstart-mp-server
        image: ${DOCKER_REPO}:${WERCKER_GIT_COMMIT}
        ports:
        - name: quickstart-mp-server
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name:  ${OKE_IMAGESECRET}

